version: '2'
services:
    qwikrest-app:
        image: qwikrest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://qwikrest-mysql:3306/qwikrest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=qwikrest-elasticsearch:9300
        ports:
            - 8080:8080
    qwikrest-mysql:
        extends:
            file: mysql.yml
            service: qwikrest-mysql
    qwikrest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: qwikrest-elasticsearch
